// This configuration was generated by `exe/eslint_autogen`
// on 2026-02-13 01:42:32 UTC.
// The point is for the user to remove these configuration records
// one by one as the offenses are removed from the code base.

import type {Linter} from "eslint";

const config: Linter.Config[] = [
  // Offense count: 2
  {
    files: [
      "app/javascript/channels/consumer.ts",
    ],
    rules: {
      "@stylistic/object-curly-spacing": "off",
    },
  },
  // Offense count: 8
  {
    files: [
      "app/javascript/application.ts",
      "app/javascript/channels/consumer.ts",
    ],
    rules: {
      "@stylistic/semi": "off",
    },
  },
];

export default config;
