default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: justice_garden_development
  host: localhost

test:
  <<: *default
  database: justice_garden_test
  host: localhost

production:
  <<: *default
  database: justice_garden_production
